---
- name: Deploy sandbox
  hosts: localhost
  tasks:
  - name: update sandbox
    custom.bankx.sandbox:
      api_token: "5vgud9glj60q1xrd.uicpjru.xxr8jhd"
      api_endpoint: "http://127.0.0.1:8000"
      name: "team-alpha-sbx"
      owner_email: "team-alpha@bankx.com"
      size: "medium"
      ttl_days: 15
      allowed_cidrs: ["0.0.0.0/0"]
      sandbox_id: "f0379682-e55a-4ccf-8268-8c3d3704f6ce"
      resource_version: "team-alpha-sbxteam-alpha@bankx.com2026-01-2319:20:07.629505"
      state: "present"
    register: out
  - name: dump output
    debug:
      msg: '{{ out }}'
