events {}

http {
    upstream appservers {
        # This uses the internal IPs but will work because the VMs are in the same VPC network
        {% for host in groups['gcp_role_appserver'] %}
        server {{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }}:8080;
        {% endfor %}

        # This uses the external IPs
        # {% for host in groups['gcp_role_appserver'] %}
        # server {{ hostvars[host]['ansible_host'] }}:8080;
        # {% endfor %}

    }
    server {
        listen 80;
        location / {
            proxy_pass http://appservers;
        }
    }
}